# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_movie_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, b'Undefined'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name=b'Rating (stars)'),
        ),
    ]
